[package]
name = "zrc_server"
version = "0.1.0"
authors = ["陆离 <sirzenith@163.com>"]
edition = "2018"

["lib"]
name = "zrc_server"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
rocket = "0.4.6"
strfmt = "0.1.6"
rusqlite = { version = "0.14.0", features = ["bundled"] }
serde = { version = "1.0.59", features = ["derive"] }
serde_json = "1.0.59"
structopt= "0.3.20"

[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["sqlite_pool", "json", "serve"]
