include $(THEOS)/makefiles/common.mk

export ARCHS = arm64

TOOL_NAME = zrc_server
zrc_server_FILES = main.mm
zrc_server_LDFLAGS = /Users/zenith/Developer/zrc-server-rs/target/aarch64-apple-ios/release/libzrc_server.a

include $(THEOS_MAKE_PATH)/tool.mk

